### ISSUE TITLE
Receive, print, and store images

### ISSUE THREAD

**Issue by JellyEvan** [JellyEvan/547final_jks#15]
receive images (in string),convert to image file types, able to print and store via GUI

**Comment by JellyEvan** [comment]
@wesleyk-duke @gs172  I am straight up using the modules from [here](https://github.com/dward2/BME547/blob/master/Lectures/image_encoding_decoding.md)

so for the server just expect the client to send RAW spectrum and background jsonified b64 strings

**Comment by gs172** [comment]
To clarify, my OCT processing code does not actually require the client to upload a raw background spectrum since that is an additional step that requires additional memory and time.

Instead, I take the client-input raw spectrum and subtract the mean A-line repeated over the size of the spectrum from itself. This is the same thing as background subtraction without having the client upload 2 separate spectrums
