### ISSUE TITLE
Upload to VM

### ISSUE THREAD

**Issue by JellyEvan** [JellyEvan/547final_jks#53]

**Comment by wesleyk-duke** [comment]
Server is now up on VM. API keys you can use:
requests.post("http://vcm-9278.vm.duke.edu:5000/add_raw_image", json=app_to_server)
image = requests.get("http://vcm-9278.vm.duke.edu:5000/get_processed_image/<filename>")

You cannot upload duplicate images so if you need to for any reason I put in this API call:
requests.get("http://vcm-9278.vm.duke.edu:5000/delete_all_images")

that will delete all of the files in the MongoDB database. I might delete this before we turn it in since it's just so you guys can more easily test out the server code

**Comment by wesleyk-duke** [comment]
This is sample code to process the image you get from the get_processed_image call:

```
a = image.text
a = a[1:]
a = a[:-1]
a = a.split(", ")
a = [float(i) for i in a]
a = np.asarray(a)
a = np.reshape(a, (app_to_server["ydim"], app_to_server["ydim"]))

plt.imshow(a, cmap='gray')
plt.colorbar()
plt.show()
```
